services:
  api:
    build: .
    image: portfolio:latest
    container_name: portfolio
    volumes:
      - ./app:/app:rw
      - ./data:/data:rw
    working_dir: /app
    ports:
      - ${API_EXT_PORT}:${API_INT_PORT}
    env_file: .env
    entrypoint: ["/scripts/entrypoint.sh"]
    command: ["air", "-c", ".air.toml"]


