services:
  exec-api:
    build: ./apps/exec-api
    image: exec-api:latest
    container_name: exec-api
    volumes:
      - ./apps/exec-api:/app:rw
      - ./apps/exec-api/data:/data:rw
    working_dir: /app
    ports:
      - ${API_EXT_PORT}:${API_INT_PORT}
    env_file: .env
    entrypoint: ["/scripts/entrypoint.sh"]
    command: ["air", "-c", ".air.toml"]
  calculator:
    build: ./apps/calc
    image: calculator:latest
    container_name: calculator
    volumes:
      - ./apps/calc:/app:rw
    working_dir: /app
