// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"encoding/json"
	"time"
)

type Portfolio struct {
	ID              int32           `json:"id"`
	UserID          int32           `json:"user_id"`
	TargetPortfolio json.RawMessage `json:"target_portfolio"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type Stock struct {
	ID        int32     `json:"id"`
	Ticker    string    `json:"ticker"`
	Price     int32     `json:"price"`
	Tradable  bool      `json:"tradable"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
