// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: portfolio.sql

package sqlc

import (
	"context"
)

const getPortfolioByUserID = `-- name: GetPortfolioByUserID :one
SELECT id, user_id, target_portfolio, created_at, updated_at FROM portfolios WHERE user_id = $1
`

func (q *Queries) GetPortfolioByUserID(ctx context.Context, userID int32) (Portfolio, error) {
	row := q.db.QueryRowContext(ctx, getPortfolioByUserID, userID)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetPortfolio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
