// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	GetPortfolioByUserID(ctx context.Context, userID int32) (Portfolio, error)
	GetStocksByTickers(ctx context.Context, dollar_1 []string) ([]Stock, error)
	ListStocks(ctx context.Context) ([]Stock, error)
}

var _ Querier = (*Queries)(nil)
