// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stocks.sql

package sqlc

import (
	"context"

	"github.com/lib/pq"
)

const getStocksByTickers = `-- name: GetStocksByTickers :many
SELECT id, ticker, price, tradable, created_at, updated_at FROM stocks WHERE ticker = ANY($1::varchar[])
`

func (q *Queries) GetStocksByTickers(ctx context.Context, dollar_1 []string) ([]Stock, error) {
	rows, err := q.db.QueryContext(ctx, getStocksByTickers, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stock{}
	for rows.Next() {
		var i Stock
		if err := rows.Scan(
			&i.ID,
			&i.Ticker,
			&i.Price,
			&i.Tradable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStocks = `-- name: ListStocks :many
SELECT id, ticker, price, tradable, created_at, updated_at FROM stocks
`

func (q *Queries) ListStocks(ctx context.Context) ([]Stock, error) {
	rows, err := q.db.QueryContext(ctx, listStocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stock{}
	for rows.Next() {
		var i Stock
		if err := rows.Scan(
			&i.ID,
			&i.Ticker,
			&i.Price,
			&i.Tradable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
