// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trade.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const createTrade = `-- name: CreateTrade :one
INSERT INTO trades (user_id, amount, target_portfolio, orders, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, user_id, amount, target_portfolio, orders, status, created_at, updated_at
`

type CreateTradeParams struct {
	UserID          int32           `json:"user_id"`
	Amount          int32           `json:"amount"`
	TargetPortfolio json.RawMessage `json:"target_portfolio"`
	Orders          json.RawMessage `json:"orders"`
	Status          string          `json:"status"`
}

func (q *Queries) CreateTrade(ctx context.Context, arg CreateTradeParams) (Trade, error) {
	row := q.db.QueryRowContext(ctx, createTrade,
		arg.UserID,
		arg.Amount,
		arg.TargetPortfolio,
		arg.Orders,
		arg.Status,
	)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.TargetPortfolio,
		&i.Orders,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
